projects:
  onechanhs-api:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ca-central-1
        apiId: uawusirgujavffiymdvu3cqdhq
        maxDepth: 2
extensions:
  amplify:
    version: 3
